from barcode.writer import ImageWriter
import barcode
import rich
from rich import print
import datetime
from PIL import Image

number = input("Type the number to be generated by the QR [11 digits]: ")
format = barcode.get_barcode_class("upc")

barcode_output = format(number, writer=ImageWriter())

formatted_time = datetime.datetime.now().strftime("%H-%M-%S %d%m%Y")
file_name = f"bar_{formatted_time}"
barcode_output.save(file_name)


Image.open(f"{file_name}.png").show()
